# This file will be regenerated by `mulle-sourcetree-to-cmake` via
# `mulle-sde reflect` and any edits will be lost.
#
# This file will be included by cmake/share/Files.cmake
#
# Disable generation of this file with:
#
# mulle-sde environment set MULLE_SOURCETREE_TO_CMAKE_LIBRARIES_FILE DISABLE
#
if( MULLE_TRACE_INCLUDE)
   message( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

#
# Generated from sourcetree: 6985D83C-7C14-4163-A97D-AC6C75028D06;m;no-build,no-cmake-inherit,no-delete,no-dependency,no-fs,no-import,no-share,no-update;
# Disable with : `mulle-sourcetree mark m `
# Disable for this platform: `mulle-sourcetree mark m no-cmake-platform-${MULLE_UNAME}`
# Disable for a sdk: `mulle-sourcetree mark m no-cmake-sdk-<name>`
#
if( COLLECT_ALL_LOAD_OS_SPECIFIC_LIBRARIES_AS_NAMES)
   list( APPEND ALL_LOAD_OS_SPECIFIC_LIBRARIES "m")
else()
   if( NOT M_LIBRARY)
      foreach( _TMP_M_LIBRARY_TARGET m)
         if( TARGET ${_TMP_M_LIBRARY_TARGET})
            set( M_LIBRARY ${_TMP_M_LIBRARY_TARGET})
            break()
         endif()
      endforeach()
      if( NOT M_LIBRARY)
         find_library( M_LIBRARY NAMES
            m
         )
      endif()
      message( STATUS "M_LIBRARY is ${M_LIBRARY}")
   endif()
   if( M_LIBRARY)
         #
         # Add M_LIBRARY to ALL_LOAD_OS_SPECIFIC_LIBRARIES list.
         # Disable with: `mulle-sourcetree mark m no-cmake-add`
         #
         if( NOT ${M_LIBRARY} IN_LIST ALL_LOAD_OS_SPECIFIC_LIBRARIES)
            list( APPEND ALL_LOAD_OS_SPECIFIC_LIBRARIES ${M_LIBRARY})
         endif()
         # intentionally left blank
   else()
      # Disable with: `mulle-sourcetree mark m no-require-link`
      message( SEND_ERROR "M_LIBRARY was not found in m")
   endif()
endif()
