#! /bin/sh
#
#   Copyright (c) 2022 Nat! - Mulle kybernetiK
#   All rights reserved.
#
#   Redistribution and use in source and binary forms, with or without
#   modification, are permitted provided that the following conditions are met:
#
#   Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
#   Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
#   Neither the name of Mulle kybernetiK nor the names of its contributors
#   may be used to endorse or promote products derived from this software
#   without specific prior written permission.
#
#   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#   AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#   IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#   ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#   LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#   CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#   SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#   INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#   CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#   ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#   POSSIBILITY OF SUCH DAMAGE.
#
[ "${TRACE:-}" = 'YES' -o "${MULLE_MARKDOWN_PREVIEW_TRACE:-}" = 'YES' ] && set -x && : "$0" "$@"


md="${1:-README.md}"

# file must be in local to find images
html="`mktemp mulle-markdown-preview-XXXXXX.html`" || exit 1

remove_metadata()
(
   local line
   local found

   IFS=$'\n'
   while read -r line
   do
      case "${line}" in
         \-\-\-*)
            if [ -z "${found}" ]
            then
               found='YES'
               continue
            fi

            # emit rest unchecked
            break
         ;;

         '')
            # ignore empty at top and in metadata
            # if we are outside, we are not in this loop anymore
            continue
         ;;

         *)
            # if in metadata ignore
            if [ "${found}" = 'YES' ]
            then
               continue
            fi

            # not in metadata and not empty, so no metadata, emit all
            printf "%s\n" "${line}"
            break
         ;;
      esac
   done

   while read -r line
   do
      printf "%s\n" "${line}"
   done
   return
)


#
# MEMO: xdg-open returns immediately, so we can't immediately remove the
# preview file
#
if remove_metadata < "${md}" | mulle-markdown -m  > "${html}"
then
   case "`uname`" in
      *arwin*)
         open "${html}"
         if [ "${MULLE_MARKDOWN_PREVIEW_KEEP_HTML}" != 'YES' ]
         then
            sleep 10
            rm "${html}"
         fi
      ;;

      *inux*)
         xdg-open "${html}"
         if [ "${MULLE_MARKDOWN_PREVIEW_KEEP_HTML}" != 'YES' ]
         then
            sleep 10
            rm "${html}"
         fi
      ;;

      *)
         mv "${html}" .
         echo "`basename -- "${html}"` is ready"
      ;;
   esac
fi
