/*
 *   This file will be regenerated by `mulle-match-to-c` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_MATCH_TO_C_C_HEADERS_FILE DISABLE
 *
 *   To not let mulle-match-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_MATCH_TO_C_RUN DISABLE
 */
#ifndef mulle_markdown_provide_h__
#define mulle_markdown_provide_h__


#include "make-style.css.inc"
#include "mulle-markdown-version.h"
#include "style.css.inc"


#endif
