name: Artifacts

# this will only happen if a "Release" page is being built
on:
  release:
     types: [ prereleased, released ]
  workflow_dispatch:

env:
  BUILD_TYPE: release
  OTHER_PROJECTS: "MulleFoundation/mulle-foundation-developer;
mulle-objc/mulle-objc-developer;
mulle-c/mulle-c-developer;"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]

    steps:
    - name: Add to path
      run:  echo "$HOME/bin" >> $GITHUB_PATH

    - uses: actions/checkout@v3

    - uses: mulle-sde/github-ci@v1

    - uses: mulle-cc/github-ci@v4

    - name: Mulle-SDE Craft
      run: mulle-sde -DMULLE_CRAFT_SDKS=cosmopolitan craft --${BUILD_TYPE}

    - name: Get Executable
      run: echo "exepath=$(mulle-sde product)" >> $GITHUB_OUTPUT
      id: executable

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: artifact.cosmopolitan
        path: ${{ steps.executable.outputs.exepath }}
        retention-days: 1

  release:
    needs: [ build ]
    name: Upload Artifacts to Release
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: artifact.cosmopolitan
          # actual file will be ${{ steps.executable.outputs.exepath }} though!

      - name: Upload asset to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ steps.executable.outputs.exepath }}
          asset_name: artifact.cosmopolitan
          asset_content_type: application/octet-stream
